### PR TITLE
Add date_query support

### PR DESCRIPTION
**Pull request by DrewAPicture**
As requested in #38, this PR implements date_query support for a single date query.

This would be considered "phase 1" with the option to later add support for incremented (multiple) date queries. The reasoning for not including multiples with this PR, is that while the logical progression is to move to supporting multiples in the future, it would probably be best to first nail down the best approach to implementing a single date query in terms of attribute naming and architecture :)

Note: In the attribute descriptions below, you'll notice that I reference the "top-level" and "second-level" areas of the date query. Top-level arguments serve in a "global" capacity to all date queries contained on the second-level. The actual individual date queries are defined on the second-level of the associative array.

This introduces a total of 8 new attributes (yikes, I know):
- `date`
  — Serves as a shortcut to setting the 'year', 'month', and 'day' arguments for a given date query struct on the second-level. It accepts either a strictly-formatted 'YYYY-MM-DD' date string or a relative-formatted date string, such as 'Sunday, September 7'. The relative-formatted string is intended as a fallback for the easier-to-sanitize 'YYYY-MM-DD' formatted string and could prove fickle when supplied with too little information.
- `date_column`
  — The first of two top-level arguments, this serves as the "global" column to query for all date queries in the date query arrays on the second-level. This defaults to 'post_date'.
- `date_compare`
  — The second of two top-level arguments, this serves as the "global" comparison operator for all date queries in the date query arrays on the second-level. This defaults to '='.
- `date_query_before`
  — Sets the 'before' argument for a date query on the second level. It accepts either a strictly-formatted date, 'YYYY-MM-DD', or as a fallback, a relative-formatted date string (using the same logic as the `date` attribute).
- `date_query_after`
  — Sets the 'after' argument for a date query on the second level. Like the `date_query_before` attribute, It accepts either a a strictly-formatted date, 'YYYY-MM-DD', or as a fallback, a relative-formatted date string (using the same logic as the `date` attribute.
- `date_query_column`
  — Sets the column to query by for the second-level date query. If not set, falls back to the value of `date_column`.
- `date_query_compare`
  — Sets the comparison operator for the second-level date query. If not set, falls back to the value of `date_compare`.
- `time`
  — Serves as a shortcut to populating the 'hour', 'minute', and 'second' arguments in the second-level date query. It accepts only a strictly-formatted string in the format of 'HH:MM:SS' or 'HH:MM'. This does NOT have a string falback.

It also introduces a new function, `be_sanitize_date_time()` for handling date and time sanitization, as this logic is reused in 3 or 4 different instances, I thought it best to keep it DRY :)

`be_sanitize_date_time()` includes a filter though it does not include the early-return-fallback logic at the top.

Here are some sample shortcodes:
**Query for posts published on a specific date**:

```
[display-posts date="2014-09-07"]
[display-posts date="Sunday, September 9, 2014"]
```

**Query for posts published after January 1, 2013**:

```
[display-posts date_query_after="2013-01-01"]
[display-posts date_query_after="January 1, 2013"]
```

**Query for posts published BEFORE today**:

```
[display-posts date_query_before="Today"]
```

**Query for posts modified yesterday**:

```
[display-posts date="Yesterday" date_query_column="post_modified"]
```

### CODE REVIEW

**Comment by Lyallpuria** [comment]
How to display the posts of only **"Current Day"**?
Using specific date, i can achieve my object but i need to change the date daily.

Please urgent reply

**Comment by billerickson** [comment]
@Lyallpuria `[display-posts date="today"]`

**Comment by Lyallpuria** [comment]
I have applied in this date code in the following way

[display-posts **date="today"** category="Dawn" no_posts_message="No Job Published in Dawn Newspapers Today." posts_per_page="150"]

but this is not working so I have applied the following as usual

[display-posts **date="2018-12-12"** category="Dawn" no_posts_message="No Job Published in Dawn Newspapers Today." posts_per_page="150"]

I am using **_IsleMag_** theme and This plugin has not been tested with version of WordPress.

Plz spend your precious time for this issue.

thanks

**Comment by SpiritSchool** [comment]
> How to display the posts of only **"Current Day"**?
> Using specific date, i can achieve my object but i need to change the date daily.
> 
> Please urgent reply

this code has not worked on my website. if there is any other code, then please tell me

**Comment by SpiritSchool** [comment]
> @Lyallpuria `[display-posts date="today"]`

no working plz. tell new code of today.

**Comment by SpiritSchool** [comment]
Yes working. Thank you.

**Comment by Lyallpuria** [comment]
**[display-posts date_query_after="yesterday"]**
its working but when you insert category attribute, it shows also yesterday posts

I have applied the following code and see the result in attached picture
[display-posts **Category="dunya"** date_query_after="Yesterday" posts_per_page="150" include_date="true" ]

ice_screenshot_20181217-154646

**Comment by Lyallpuria** [comment]
> Yes working. Thank you.

Spirit, yes its working but please test with category attribute.

**Comment by SpiritSchool** [comment]
\

> > Yes working. Thank you.
> 
> Spirit, yes its working but please test with category attribute.

I didnt check it with category attr.

**Comment by Lyallpuria** [comment]
Try "List category posts" plugin
[catlist  **after="-1 days**"]

**Comment by SpiritSchool** [comment]
hmmm. I'll. thanks Lyallpuria

**Comment by brunogabuzomeu** [comment]
This syntax is working:
`[display-posts date_query_after="-1 months"]`

**Comment by magnetarsaurus** [comment]
Hi there,

I'm using your plugin (thank you!!) and implemented it as follows: 
[display-posts date_query_before="-1 days" date_query_after="-2 days"] 
[display-posts date_query_before="-2 days" date_query_after="-3 days"] 
[display-posts date_query_before="-3 days" date_query_after="-4 days"] 

etc etc, hoping that i would get a list of posts for every day of the week.

The problem is, that during the day some posts move to the column of the previous day (rather than wait until 0:00h). 

Do you have any idea what causes this behaviour? If so, is there a solution for it?

Thanks in advance!

Best,
Robin

**Comment by juanalan** [comment]
Hello guys
I need some help on the plugin, connected to the WP Events Manager plugin.

I use in shortcodes date_query_after:
[display-posts post_type=”event_listing” s=”Tartempion” orderby=”_event_start_date” date_query_after=”today”]

But it doesn’t work ! Same for the date_query_before !
Is it because the date_query_xxx item uses only the modification date ? or publication date ?

thx a lot for your help

**Comment by billerickson** [comment]
@juanalan Date queries in WordPress are for the published date or modified date. 

WP Events Manager is likely storing the event date as metadata, so you should use a meta query. Here are some examples:

- [Display upcoming events from The Events Calendar](https://displayposts.com/2019/01/04/display-upcoming-events-from-the-events-calendar/)
- [Display upcoming events from Sugar Events Calendar](https://displayposts.com/2019/01/03/display-upcoming-events-from-sugar-event-calendar/)

I recommend contacting WP Events Manager to find out the proper meta keys for querying their data.

**Comment by juanalan** [comment]
hello Billy
Thanks for your answer. Until now, they haven't tell me useful informations. But I will try again.
Nevertheless, even with the Events Calendar plugin, your example doesn't seem to work (I use your code in a snippet to test it).
An issue ?

Thanks again for your help

JA

**Comment by billerickson** [comment]
Those code snippets were functional when written in 2019. I'm not sure if the post type or meta key has changed. 

The general idea is you need to query based on the post type (ex: `tribe_events` ) and the meta field that stores the event date (ex: `_EventStartDate`)

**Comment by juanalan** [comment]
The post_type is "event_listing" and the event date seems to be "event_start_date" (or "_event_start_date").
Nevertheless, I don't understand how to do with the examples.
Can you help me ?
JA

**Pull request merged**
