### PR TITLE
Add option to remove links from posts

### PR DESCRIPTION
**Pull request by JiveDig**
New parameter of link_posts => true to optionally disable linking of posts.
New conditional check to see if post_type is public before adding links.

My editor removes whitespace/spaces on save, that's the reason for the extra changes in here. Hopefully not an issue.

### CODE REVIEW

**Comment by billerickson** [comment]
Sorry, I'm a bit swamped at the moment. I'll try to take a look at it over the weekend.

One thing I will change is the parameter name. I'd prefer `'include_link' => true` as that will match the naming convention of the other parameters (include_title, include_content...).

**Comment by JiveDig** [comment]
Cool. Just updated the PR with the new name.
I was also considering adding logic within the read more link stuff, but I think that's unnecessary. A user shouldn't go out of their way to set the more link parameter if they are also setting include_link to false. A conflict could occur if excerpts were used for something else, and/or the_excerpt filter was doing something tricky, but I don't think DPS should worry about it.

**Comment by billerickson** [comment]
I've added the include_link parameter.

Can you explain to me the point of checking whether the post type is public? I didn't include that because I couldn't imagine a use case where you would be publicly querying and displaying a non-public post type and expecting the links to not appear. 

If there is some strange situation where you are querying a non-public post type, you can also use the include_link="false" parameter.

**Comment by JiveDig** [comment]
No prob. Sometimes I register a private post type called Testimonials, but allow it to be publicly queryable. This way I can show random testimonials via the shortcode throughout the site. I'm not sure my PR handled that scenario the best way, and it's possibly not even worth it since anyone skilled enough to register a private CPT should be able to use the shortcode accordingly.

**Pull request closed without merging**
